---
title: "Shotgun - Functional Annotation Results"
author: "Nate Olson"
date: "6/29/2018"
output: html_document
---

```{r}
library(ProjectTemplate)
load.project()
```

## Filtering antibiotic resistance genes
```{r}
library(readxl)
ar_genes <- read_excel("data/raw_data/ar_tox_genes.xlsx", 
                       sheet = 1, range = "B2:C320") %>% 
    rename(gene_name = `Relevant genes from ARDB`) %>% 
    mutate(predicted_gene_name = toupper(gene_name))
```

Calculating gene ratio - normalizing by proportions
```{r}
gene_ratio <- funct_anno_df %>% 
    group_by(Sample_ID) %>% 
    mutate(total_count = n()) %>% 
    group_by(Sample_ID, predicted_gene_name) %>% 
    mutate(gene_count = n(),
           gene_prop = gene_count / total_count) %>% 
    select(Sample_ID, predicted_gene_name, gene_count, total_count, gene_prop) %>% 
    distinct()
```

```{r}
gene_ratio
```

```{r}
anno_gene_filt <- gene_ratio %>% 
    left_join(ar_genes)
```

```{r}
anno_gene_filt
```


```{r}
glimpse(anno_gene_filt)
```

Number of antibiotic genes per sample
```{r}
anno_gene_filt_tbl <- anno_gene_filt %>% 
    filter(!is.na(gene_name)) %>% 
    # separate(Sample_ID,c("Sample_Code", "Collection_Date", "Sample_Type"), 
    #          sep = "_",remove = FALSE) %>% 
    group_by(Antibiotic, gene_name, Sample_ID) %>% 
    summarise(count = n()) %>% 
    spread(Sample_ID, count, fill = 0)
anno_gene_filt_tbl
    
```

Looking at Chloramphenicol by sample as an example. 
Pick chloramphenicol few genes with a good number of observations, basically good for plotting.
```{r}
anno_gene_filt %>% 
    filter(Antibiotic == "Chloramphenicol") %>% 
    separate(Sample_ID,c("Sample_Code", "Collection_Date", "Sample_Type"), 
             sep = "_") %>% 
    # mutate(Collection_Date = as.Date(Collection_Date)) %>% 
    filter(Sample_Type == "W") %>% 
    ggplot() + geom_bar(aes(x = Collection_Date, y = gene_prop,
                            fill = Sample_Code), 
                        color = "grey20",
                        stat = "identity",
                        position = "dodge") + 
    facet_wrap(~gene_name, scales = "free_x") + 
    coord_flip() + theme_bw()
``` 

```{r}
anno_gene_filt %>% 
```

