---
title: "zvi_beta_diversity"
author: "Prachi Kulkarni"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---
```{r}
knitr::opts_chunk$set(echo=TRUE)
```

```{r loading packages, warning=FALSE, message=FALSE, echo = FALSE}
# Load required packages
library(ape)
library(dplyr)
library(ggplot2)
library(gplots)
library(lme4)
library(plotly)
library(tidyr)
library(vegan)
library(phyloseq)
library(data.table)
library(readr)
library(tidyr)
library(stringr)
library(magrittr)
library(tibble)
library(knitr)
library(devtools)
library(metagenomeSeq)
library(broom)
library(iNEXT)
library(ggExtra)
library(DT)
library(purrr)
library(ggfortify)
library(rmarkdown)
```



```{r loading phyloseq object and subsetting it, warning=FALSE, message=FALSE,echo = FALSE}
# Load phyloseq object (ZVI phyloseq Object "zpo")
zpo = readRDS("phyloseq.RDS")

# Subset phyloseq object so that only water samples NR, CE, RB, RW, ZW and TW are included
zpow1 = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NC"
 & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL"
 & Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS")

# Subset phyloseq object so that only water samples RW, ZW and TW are included
zpow = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR"& Sample_Code != "NC"
  & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL"
 & Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS"
 & Sample_Code !="CE" & Sample_Code !="RB")

# Subset phyloseq object so that only lettuce samples RL,ZL and TL are included
zpol = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR"& Sample_Code != "NC"
                      & Sample_Code != "RW"& Sample_Code != "ZW"& Sample_Code != "TW"& Sample_Code != "CE"& Sample_Code != "RB"
                      & Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS")

# Subset phyloseq object so that only soil samples RS,ZS and TS are included
zpos = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR"& Sample_Code != "NC"
  & Sample_Code != "RW"& Sample_Code != "ZW"& Sample_Code != "TW"& Sample_Code != "CE"& Sample_Code != "RB"
 & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL")

# Subset phyloseq object so that only control and background samples BG, NC and NI are included
zpob = subset_samples(zpo, Sample_Code != "RS" & Sample_Code != "ZS" & Sample_Code != "TS"
  & Sample_Code != "RW"& Sample_Code != "ZW"& Sample_Code != "TW"& Sample_Code != "CE"& Sample_Code != "RB" & Sample_Code != "NR" & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL")


# Set up variable for downstream analysis
zo1 = zpow1
zo2 = zpow
zo3 = zpol
zo4 = zpos
zo5 = zpob
```


```{r RW, ZW, TW, CE, RB and NR beta diversity, echo = FALSE}
### Rw, ZW, TW, CE, RB and NR Beta Diversity Analysis - Nate's Code for WWTP Community Analysis
dist_methods <- unlist(distanceMethodList)[c(8,10)]

zo_pcoa_list <- list()
zo_nmds_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo1, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo1, method = "PCoA", distance = iDist)
  zo_nmds_list[[i]] <- ordinate(zo1, method = "NMDS", distance = iDist)
}

### Ordination Plots


plot_ordination(zo1, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo1, zo_nmds_list[[1]], color= "Sample_Code", title = "Bray Curtis NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[1]])

#### Jaccard

plot_ordination(zo1,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo1, zo_nmds_list[[2]], color= "Sample_Code", title = "Jaccard NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[2]])

### Testing for Differences

iDist <- distance(zo1, method = "bray")

anosim(iDist,grouping = factor(zo1@sam_data$Sample_Code))

## betadisper has a post-hoc test

iDist <- distance(zo1, method = "bray")

beta_fit <- betadisper(iDist,group = factor(zo1@sam_data$Sample_Code))

anova(beta_fit) %>% tidy() %>% kable()

TukeyHSD(beta_fit)$group %>% as.data.frame() %>% 
  rownames_to_column(var = "comparison") %>% 
  filter(`p adj` < 0.05) %>% kable(digits = 3)
```

```{r echo = FALSE}
### Rw, ZW and TW Beta Diversity Analysis - Nate's Code for WWTP Community Analysis
dist_methods <- unlist(distanceMethodList)[c(8,10)]
# ask Nate why c(8,10)?

zo_pcoa_list <- list()
zo_nmds_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo2, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo2, method = "PCoA", distance = iDist)
  zo_nmds_list[[i]] <- ordinate(zo2, method = "NMDS", distance = iDist)
}

### Ordination Plots


plot_ordination(zo2, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo2, zo_nmds_list[[1]], color= "Sample_Code", title = "Bray Curtis NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[1]])

#### Jaccard

plot_ordination(zo2,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo2, zo_nmds_list[[2]], color= "Sample_Code", title = "Jaccard NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[2]])

### Testing for Differences

iDist <- distance(zo2, method = "bray")

anosim(iDist,grouping = factor(zo2@sam_data$Sample_Code))

## betadisper has a post-hoc test

iDist <- distance(zo2, method = "bray")

beta_fit <- betadisper(iDist,group = factor(zo2@sam_data$Sample_Code))

anova(beta_fit) %>% tidy() %>% kable()

TukeyHSD(beta_fit)$group %>% as.data.frame() %>% 
  rownames_to_column(var = "comparison") %>% 
  filter(`p adj` < 0.05) %>% kable(digits = 3)
```

```{r echo = FALSE}
### RL, ZL and TL Beta Diversity Analysis - Nate's Code for WWTP Community Analysis
dist_methods <- unlist(distanceMethodList)[c(8,10)]

zo_pcoa_list <- list()
zo_nmds_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo3, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo3, method = "PCoA", distance = iDist)
  zo_nmds_list[[i]] <- ordinate(zo3, method = "NMDS", distance = iDist)
}

### Ordination Plots


plot_ordination(zo3, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo3, zo_nmds_list[[1]], color= "Sample_Code", title = "Bray Curtis NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[1]])

#### Jaccard

plot_ordination(zo3,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo3, zo_nmds_list[[2]], color= "Sample_Code", title = "Jaccard NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[2]])

### Testing for Differences

iDist <- distance(zo3, method = "bray")

anosim(iDist,grouping = factor(zo3@sam_data$Sample_Code))
```

```{r echo = FALSE}
### RS, ZS and TS Beta Diversity Analysis - Nate's Code for WWTP Community Analysis
dist_methods <- unlist(distanceMethodList)[c(8,10)]

zo_pcoa_list <- list()
zo_nmds_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo4, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo4, method = "PCoA", distance = iDist)
  zo_nmds_list[[i]] <- ordinate(zo4, method = "NMDS", distance = iDist)
}

### Ordination Plots


plot_ordination(zo4, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo4, zo_nmds_list[[1]], color= "Sample_Code", title = "Bray Curtis NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[1]])

#### Jaccard

plot_ordination(zo4,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo4, zo_nmds_list[[2]], color= "Sample_Code", title = "Jaccard NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[2]])

### Testing for Differences

iDist <- distance(zo4, method = "bray")

anosim(iDist,grouping = factor(zo4@sam_data$Sample_Code))
```

```{r echo = FALSE}
### Background samples Beta Diversity Analysis - Nate's Code for WWTP Community Analysis
dist_methods <- unlist(distanceMethodList)[c(8,10)]

zo_pcoa_list <- list()
zo_nmds_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo5, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo5, method = "PCoA", distance = iDist)
  zo_nmds_list[[i]] <- ordinate(zo5, method = "NMDS", distance = iDist)
}

### Ordination Plots


plot_ordination(zo5, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo5, zo_nmds_list[[1]], color= "Sample_Code", title = "Bray Curtis NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[1]])

#### Jaccard

plot_ordination(zo5,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

plot_ordination(zo5, zo_nmds_list[[2]], color= "Sample_Code", title = "Jaccard NMDS") + theme_bw()+stat_ellipse()

stressplot(zo_nmds_list[[2]])

### Testing for Differences

iDist <- distance(zo5, method = "bray")

anosim(iDist,grouping = factor(zo5@sam_data$Sample_Code))
```


