---
title: "ZVI Beta Diversity Figures"
author: "Prachi Kulkarni"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
---

```{r message = FALSE, warning = FALSE, echo = FALSE}
library(knitr)
library(phyloseq)
library(ggpubr)
library(tidyverse)
opts_chunk$set(cache = TRUE, message = FALSE, warning = FALSE, echo = FALSE)
```


```{r}
# Load phyloseq object (ZVI phyloseq Object "zpo")
zpo <- readRDS("phyloseq.RDS")

zpo <- prune_taxa(zpo, Rank6 != "Cyanobacteria")  

# Subset phyloseq object so that only RW, ZW, TW, RL, ZL and TL are included
zpo1 <- subset_samples(zpo, Sample_Code %in% c("RW","ZW","TW","RL","ZL","TL"))

# Subset phyloseq object so that only water samples RW and ZW are included
zpo2 = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR" & Sample_Code !="TW" & Sample_Code != "NC" & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL" & Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS" & Sample_Code !="CE" & Sample_Code !="RB")

# Subset phyloseq object so that only lettuce samples RL,ZL and TL are included
zpo3 = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR"& Sample_Code != "NC" & Sample_Code != "RW"& Sample_Code != "ZW"& Sample_Code != "TW"& Sample_Code != "CE"& Sample_Code != "RB"& Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS")

# Subset phyloseq object so that all samples except background samples are included 
zpo4 = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR"& Sample_Code != "NC")

#Subset phyloseq object so that only CE, RB, RW and ZW samples are included
zpo5 = subset_samples(zpo, Sample_Code != "NI" & Sample_Code != "BG" & Sample_Code != "NR" & Sample_Code !="TW" & Sample_Code != "NC" & Sample_Code != "RL"& Sample_Code != "ZL"& Sample_Code != "TL" & Sample_Code != "RS"& Sample_Code != "ZS"& Sample_Code != "TS")


# Set up variable for downstream analysis
zvi_ps_list <- list(all_exp = zpo1, 
                    rw_v_zw = zpo2, 
                    lettuce = zpo3, 
                    kitchen_sink = zpo4, 
                    storage = zpo5)
zo1 = zpo1
zo2 = zpo2
zo3 = zpo3
zo4 = zpo4
zo5 = zpo5
```


```{r zo1}
# RW, ZW, TW, RL, ZL, TL Bray Curtis, Jaccard, Weighted and unweighted unifrac PCOA plots and differences

dist_methods <- unlist(distanceMethodList)[c(1,2,8,10)]

zo_pcoa_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo1, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo1, method = "PCoA", distance = iDist)
}

### Bray Curtis
p1 = plot_ordination(zo1, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

#### Jaccard
p2 = plot_ordination(zo1,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

#### Unifrac
p3 = plot_ordination(zo1, zo_pcoa_list[[3]], color = "Sample_Code", title = "Unifrac PCoA") +
  theme_bw()+stat_ellipse()

#### Weighted Unifrac
p4 = plot_ordination(zo1, zo_pcoa_list[[4]], color = "Sample_Code", title = "weighted Unifrac PCoA")+
  theme_bw()+stat_ellipse()

ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2, common.legend = TRUE)
```

```{r ord_setup}
ord_fun <- function(ps, dist_method) {
    iDist <- distance(ps, method = dist_method)
    # Calculate ordination
    ordinate(ps, method = "PCoA", distance = iDist)
}
zvi_ord_bray_list <- zvi_ps_list %>% map(ord_fun, dist_method = "bray")
zvi_ord_jaccard_list <- zvi_ps_list %>% map(ord_fun, dist_method = "jaccard")
zvi_ord_wunifrac_list <- zvi_ps_list %>% map(ord_fun, dist_method = "wunifrac")
zvi_ord_unifrac_list <- zvi_ps_list %>% map(ord_fun, dist_method = "unifrac")
```

```{r ordPlotallExp}
pcoa_plot <- function(ord, ps){
    plot_ordination(ps, ord, color = "Sample_Code") +
        theme_bw() + 
        stat_ellipse()
}

ord_list <- list(zvi_ord_bray_list[[1]], 
          zvi_ord_jaccard_list[[1]],
          zvi_ord_unifrac_list[[1]], 
          zvi_ord_wunifrac_list[[1]]) %>% 
    map(pcoa_plot, ps = zvi_ps_list[[1]])  

ggarrange(ord_list, ncol = 2, nrow = 2, common.legend = TRUE)
```


```{r }
# RW and ZW Bray Curtis, Jaccard, Weighted and unweighted unifrac PCOA plots and differences

dist_methods <- unlist(distanceMethodList)[c(1,2,8,10)]

zo_pcoa_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo2, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo2, method = "PCoA", distance = iDist)
}

### Bray Curtis
p1 = plot_ordination(zo2, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

#### Jaccard
p2 = plot_ordination(zo2,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

#### Unifrac
p3 = plot_ordination(zo2, zo_pcoa_list[[3]], color = "Sample_Code", title = "Unifrac PCoA") +
  theme_bw()+stat_ellipse()

#### Weighted Unifrac
p4 = plot_ordination(zo2, zo_pcoa_list[[4]], color = "Sample_Code", title = "weighted Unifrac PCoA")+
  theme_bw()+stat_ellipse()

ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2, common.legend = TRUE)
```


```{r zo3}
# RW and ZW Bray Curtis, Jaccard, Weighted and unweighted unifrac PCOA plots and differences

dist_methods <- unlist(distanceMethodList)[c(1,2,8,10)]

zo_pcoa_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo3, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo3, method = "PCoA", distance = iDist)
}

### Bray Curtis
p1 = plot_ordination(zo3, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

#### Jaccard
p2 = plot_ordination(zo3,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

#### Unifrac
p3 = plot_ordination(zo3, zo_pcoa_list[[3]], color = "Sample_Code", title = "Unifrac PCoA") +
  theme_bw()+stat_ellipse()

#### Weighted Unifrac
p4 = plot_ordination(zo3, zo_pcoa_list[[4]], color = "Sample_Code", title = "weighted Unifrac PCoA")+
  theme_bw()+stat_ellipse()

ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2, common.legend = TRUE)
```

```{r zo4}
# RW and ZW Bray Curtis, Jaccard, Weighted and unweighted unifrac PCOA plots and differences

dist_methods <- unlist(distanceMethodList)[c(1,2,8,10)]

zo_pcoa_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo4, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo4, method = "PCoA", distance = iDist)
}

### Bray Curtis
p1 = plot_ordination(zo4, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

#### Jaccard
p2 = plot_ordination(zo4,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

#### Unifrac
p3 = plot_ordination(zo4, zo_pcoa_list[[3]], color = "Sample_Code", title = "Unifrac PCoA") +
  theme_bw()+stat_ellipse()

#### Weighted Unifrac
p4 = plot_ordination(zo4, zo_pcoa_list[[4]], color = "Sample_Code", title = "weighted Unifrac PCoA")+
  theme_bw()+stat_ellipse()

ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2, common.legend = TRUE)
```

```{r zo5, fig.cap = "Figure legend"}
# RW and ZW Bray Curtis, Jaccard, Weighted and unweighted unifrac PCOA plots and differences

dist_methods <- unlist(distanceMethodList)[c(1,2,8,10)]

zo_pcoa_list <- list()
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(zo5, method = i)
  # Calculate ordination
  zo_pcoa_list[[i]] <- ordinate(zo5, method = "PCoA", distance = iDist)
}

### Bray Curtis
p1 = plot_ordination(zo5, zo_pcoa_list[[1]], color= "Sample_Code", title = "Bray Curtis PCoA") + theme_bw()+stat_ellipse()

#### Jaccard
p2 = plot_ordination(zo5,zo_pcoa_list[[2]], color= "Sample_Code", title = "Jaccard PCoA") + theme_bw()+stat_ellipse()

#### Unifrac
p3 = plot_ordination(zo5, zo_pcoa_list[[3]], color = "Sample_Code", title = "Unifrac PCoA") +
  theme_bw()+stat_ellipse()

#### Weighted Unifrac
p4 = plot_ordination(zo5, zo_pcoa_list[[4]], color = "Sample_Code", title = "weighted Unifrac PCoA")+
  theme_bw()+stat_ellipse()

ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2, common.legend = TRUE)
```

