---
title: "Coverage Plot"
author: "Prachi Kulkarni"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning = FALSE, echo = FALSE}
library(metagenomeSeq)
library(tidyverse)
library(iNEXT)
library(ggExtra)
opts_chunk$set(cache=TRUE, message=FALSE, warning = FALSE, echo = FALSE)
```

```{r calcDivEst}
# Load mrexperiment object
zmo = readRDS("mrexp.RDS")
# Coverage analysis with all samples included using Sample_Code
div_est <- zmo  %>% MRcounts()  %>% DataInfo()
```

```{r}
p <- ggplot(div_est, aes(x = n, y = SC)) +
  geom_point(aes(color = zmo$Sample_Code)) + scale_x_log10() + 
  geom_vline(aes(xintercept = 100), linetype = 2, color = "grey 60") + 
  theme_bw() +
  labs(x = "Number of Sequences",y = "Coverage", color = "Sample Code") +
  theme(legend.position = "bottom")
ggMarginal(p, type = "histogram", margins = "x")
```

```{r}
# Coverage analysis with all samples included using Sample_Type
p <- ggplot(div_est, aes(x = n, y = SC)) +
  geom_point(aes(color = zmo$Sample_Type)) + scale_x_log10() + 
  geom_vline(aes(xintercept = 100), linetype = 2, color = "grey 60") + 
  theme_bw() +
  labs(x = "Number of Sequences",y = "Coverage") +
  theme(legend.position = "bottom")
ggMarginal(p, type = "histogram", margins = "x")
```

